# Generated by Django 2.1.2 on 2019-06-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='imagen',
            field=models.FileField(default='null', upload_to='repuestos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.FileField(upload_to='productos/'),
        ),
    ]
