# Generated by Django 2.1.2 on 2019-06-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20190620_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='imagen',
            field=models.ImageField(upload_to='repuestos/'),
        ),
    ]
